apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: human-pose
  template:
    metadata:
      labels:
        app: human-pose
    spec:
      containers:
        - name: app
          image: pepperonipizzalarge/app
          ports:
            - containerPort: 5000
          env:
            - name: GGACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: ggaccesskeyid
                  key: GGACCESSKEYID
            - name: HMACKEY
              valueFrom:
                secretKeyRef:
                  name: hmackey
                  key: HMACKEY