name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set Service Key
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "ghactions-gc"

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "multi-cluster"
          location: "asia-south1-b "

      - name: Build
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t pepperonipizzalarge/app-gc:latest -t pepperonipizzalarge/app-gc:${{ env.SHA }} -f ./app/Dockerfile ./app

      - name: Push
        run: |-
          docker push pepperonipizzalarge/app-gc:latest

          docker push pepperonipizzalarge/app-gc:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/app-deployment app=pepperonipizzalarge/app-gc:${{ env.SHA }}
